- hosts: all
  become: yes
  tasks:
    - name: create user
      user: name=Ngawang append=yes state=present createhome=yes shell=/bin/bash

    - name: allow user to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'Ngawang ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the user
      authorized_key: user=Ngawang key={{item}}
      with_file:
        - ~/.ssh/id_rsa.pub
