# -*- mode: ruby -*-
# vi: set ft=ruby :
#
NETWORK_PREFIX = "192.168.77."
CONTROLLER_IP_START = 10
WORKER_IP_START = 20
LOAD_BALANCER_IP = 30

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false

  # Control plane nodes
  (0..1).each do |i|
    config.vm.define "controller-#{i}" do |node|
      node.vm.provider "virtualbox" do |vb|
        #vb.name = "kube-controller-#{i}"
        vb.memory = 2048
        vb.cpus = 2
      end
      node.vm.hostname = "controller-#{i}.local"
      node.vm.network "private_network", ip: NETWORK_PREFIX + "#{CONTROLLER_IP_START + i}"
    end
  end
 
  # Workder nodes
  (0..1).each do |i|
    config.vm.define "worker-#{i}" do |node|
      node.vm.provider "virtualbox" do |vb|
        #vb.name = "kube-worker-#{i}"
        vb.memory = 1024
        vb.cpus = 1
      end
      node.vm.hostname = "worker-#{i}.local"
      node.vm.network "private_network", ip: NETWORK_PREFIX + "#{WORKER_IP_START + i}"
    end
  end

  # Provision Load balancer
  config.vm.define "lb" do |node|
    node.vm.provider "virtualbox" do |vb|
      #vb.name = "kube-lb"
      vb.memory = 512
      vb.cpus = 1
    end
    node.vm.hostname = "lb.local"
    node.vm.network "private_network", ip: NETWORK_PREFIX + "#{LOAD_BALANCER_IP}"
  end

  # Ansible provisioner to add user
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbooks/add-user.yaml"
    ansible.groups = {
      "controllers" => ["controller-[0:1]"],
      "workers" => ["worker-[0:1]"],
      "lbs" => ["lb"],
      "all:vars" => {"ansible_python_interpreter" => "/usr/bin/python3"}
    }
  end
end
